### ISSUE TITLE
Extend Events to include Event ID and Data

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-notification-service#1]
To better identify notification events, include the following int he Event model: 
- Event ID: an unique string that would identify each event 
- Data: a string field to contain a full json that might include more data about the resources mentioned in the notification

In this way, eventTitle can be used to provide information about the notification

**Comment by rafaelangarita** [comment]
So, when you send a signal:

`curl -X POST http://localhost:3025/signals -H "Content-Type: application/json" -d '{"eventTitle": "test2", "instancedata": "This one weighed more than 16 megatons!!"}'`

you will send "eventId", right?

**Comment by cdparra** [comment]
Done in d0cc6ee58e8f8eca12d13eb18ff4f5b6a4c0f053. See [routes/signals.js](routes/signals.js). Simply added the following: 

```
matches = _.filter(items, function(sub) {
                return sub.eventId == signal.eventId
            });
```
