### ISSUE TITLE
Use title for subject and text for email body

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-notification-service#2]

**Comment by rafaelangarita** [comment]
For example, given the signal:

`curl -X POST http://localhost:3025/signals -H "Content-Type: application/json" -d '{"eventTitle": "test2", "instancedata": "This one weighed more than 16 megatons!!"}'`

you want to change the names of "eventTitle" for "title" and "instancedata" for "text", right?

**Comment by cdparra** [comment]
Done in d0cc6ee58e8f8eca12d13eb18ff4f5b6a4c0f053. See [routes/signals.js](routes/signals.js). Modified as follows: 

```
'http://' + conf.host, {
            json: {
		        'destination':'email',
                'to': '["' + subscription.alertEndpoint + '"]',
        	    'from':"AppCivist Bot <bot@appcivist.org>",
		        'subject': signal.title,
                'text': signal.text
            }
```
